# Site Settings
title:               Augusto S. Queiroz
tagline:             My personal webpage
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Augusto S. Queiroz"
  email:             "asq@cin.ufpe.br"
  twitter:           "Augusto_SQ"
  instagram:         "augustoq"
  github:            "AugustoQueiroz"
  facebook:          
  linkedin:          
navigation:
- title: (blog&nbsp;archive)
  url: /blog
- title: (CV)
  url: /cv
- title: (about&nbsp;me)
  url: /about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
collections:
- education
- experience